# Generated by Django 4.1.6 on 2023-02-15 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BinData',
            fields=[
                ('binId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('binLat', models.DecimalField(decimal_places=22, max_digits=25)),
                ('binLong', models.DecimalField(decimal_places=22, max_digits=25)),
                ('binType', models.CharField(choices=[('General Waste', 'General Waste'), ('Recycling', 'Recycling'), ('Plastic', 'Plastic'), ('Paper', 'Paper'), ('Cans', 'Cans'), ('Glass', 'Glass')], default='General Waste', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barcode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products')),
                ('type', models.CharField(max_length=30)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=1676473061.153512, verbose_name='Time occurred')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bindata')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
