# Generated by Django 4.1.7 on 2023-03-01 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BinData',
            fields=[
                ('binId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('binName', models.CharField(default='bin', max_length=100)),
                ('binLat', models.DecimalField(decimal_places=22, max_digits=100)),
                ('binLong', models.DecimalField(decimal_places=22, max_digits=100)),
                ('binPhoto', models.ImageField(default='figures/bins/default.jpg', upload_to='')),
                ('bin_general', models.BooleanField(default=False)),
                ('bin_recycle', models.BooleanField(default=False)),
                ('bin_paper', models.BooleanField(default=False)),
                ('bin_cans', models.BooleanField(default=False)),
                ('bin_glass', models.BooleanField(default=False)),
                ('bin_plastic', models.BooleanField(default=False)),
                ('bin_non_rec', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goalID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('target', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barcode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('weight', models.FloatField()),
                ('material', models.CharField(max_length=100)),
                ('recycle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('userGoalID', models.AutoField(primary_key=True, serialize=False)),
                ('userGoalNum', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('goal', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='home.goal')),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bindata')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('carbon', models.FloatField(default=0)),
                ('curweek', models.FloatField(default=0)),
                ('curmonth', models.FloatField(default=0)),
                ('curyear', models.FloatField(default=0)),
                ('lastRecycle', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='lastRecycle', to='home.product')),
                ('loveRecycling', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='loveRecycle', to='home.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
