# Generated by Django 4.1.7 on 2023-03-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bindata',
            name='binType',
        ),
        migrations.AddField(
            model_name='bindata',
            name='bin_cans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bindata',
            name='bin_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bindata',
            name='bin_glass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bindata',
            name='bin_paper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bindata',
            name='bin_recycle',
            field=models.BooleanField(default=False),
        ),
    ]
