# Generated by Django 4.1.7 on 2023-02-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='points2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
