# Generated by Django 4.1.7 on 2023-03-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bindata',
            name='bin_non_rec',
        ),
    ]
