# Generated by Django 4.1.7 on 2023-02-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_statistic_points2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='points2',
        ),
    ]
