# Generated by Django 4.1.7 on 2023-03-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_bindata_bintype_bindata_bin_cans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindata',
            name='binId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bindata',
            name='binLat',
            field=models.DecimalField(decimal_places=22, max_digits=100),
        ),
        migrations.AlterField(
            model_name='bindata',
            name='binLong',
            field=models.DecimalField(decimal_places=22, max_digits=100),
        ),
        migrations.AlterField(
            model_name='bindata',
            name='binName',
            field=models.CharField(default='bin', max_length=100),
        ),
    ]
