# Generated by Django 4.1.7 on 2023-03-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_bindata_binid_alter_bindata_binlat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindata',
            name='bin_non_rec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bindata',
            name='bin_plastic',
            field=models.BooleanField(default=False),
        ),
    ]
