# Generated by Django 4.1.7 on 2023-02-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_statistic_points2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goalID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
