# Generated by Django 4.1.7 on 2023-02-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_goal_goalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='userGoalID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
