# Generated by Django 4.1.7 on 2023-03-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bindata_bin_non_rec_bindata_bin_plastic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='carbon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='curmonth',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='curweek',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='curyear',
            field=models.FloatField(default=0),
        ),
    ]
